config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  root to: "panel/auctions#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'verify' => 'verification#show'
      post 'auctions' => 'auctions#create'

      match '*path', to: 'base#routing_error', via: :all
    end
  end

  namespace :panel do
    get 'lista_aukcji' => 'auctions#index', as: :list
    get 'statystyki' => 'auctions#stats', as: :stats
    get 'eksport_do_csv', to: 'auctions#export', as: :auctions_export
    post 'wyslij_kontrole', to: 'auctions#request_control', as: :request_control
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  serialize :auctioneer_data, Hash
  serialize :auction_data, Hash
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/auctions_controller.rb
module Api
  module V1
    class AuctionsController < BaseController
      def create
        if ::Auctions::Creator.perform(auction_params)
          render json: {}, status: :created
        else
          render json: {}, status: :unprocessable_entity
        end
      end

      private

      def auction_params
        params.require(:auction).permit(
          :auctioneer_id, :auction_id, :auction_provider,
          :auctioneer_data => {}, auction_data: {}
        )
      end
    end
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ::ActionController::Base
      protect_from_forgery with: :null_session

      before_action :restrict_access
      skip_before_action :verify_authenticity_token

      respond_to :json

      def routing_error
        head :bad_request
      end

      private

      def restrict_access
        head :unauthorized unless valid_api_key?(request.env['HTTP_X_HACK_YEAH_API_KEY'])
      end

      def valid_api_key?(api_key)
        api_key.eql?(A9n.api_key)
      end

      rescue_from ActiveRecord::RecordNotFound do |e|
        render json: { error: e.message }, status: :not_found
      end

      rescue_from ActionController::ParameterMissing do |e|
        render json: { error: e.message }, status: :unprocessable_entity
      end
    end
  end
end

app/controllers/api/v1/verification_controller.rb
module Api
  module V1
    class VerificationController < BaseController
      def show
        render json: { working:  true }, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/panel/auctions_controller.rb
module Panel
  class AuctionsController < ApplicationController
    before_action :authenticate_user!

    def index
      @auctions = Auction.order('created_at DESC').limit(1000)
    end

    def export
      generator = Auctions::CsvGenerator.new

      send_data generator.csv_string, filename: generator.csv_file_name
    end

    def request_control
      permitted_params = params.require(:report).permit(:auction_id, :full_description)

      ReportMailer.report(permitted_params[:auction_id], permitted_params[:full_description], current_user).deliver_now

      logger.info([current_user.id, permitted_params[:auction_id]])
    end

    def stats; end

    def logger
      @logger ||= Logger.new("#{Rails.root}/log/monitoring.log")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="pl">
  <head>
    <title>VATmobil</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
  <script>
    new Chartist.Line('.ct-chart', {
      labels: ['Środa', 'Czwartek', 'Piątek', 'Sobota', 'Niedziela'],
      series: [
        [120, 92, 73, 123, 54]
      ]
      }, {
      fullWidth: true,
      chartPadding: {
        right: 40
      }
    });
  </script>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/panel/auctions/_auction.html.erb
<tr>
  <td><a href="https://allegro.pl/show_item.php?item=<%= auction.auction_id %>"><%= auction.auction_id %></a></td>
  <td><%= auction[:auction_data]['title'] %></td>
  <td><%= Money.new(auction[:auction_data]['price'].to_i, 'PLN').format %></td>
  <td><%= auction.fraud_possibility? ? 'Podejrzany' : 'Czysty' %></td>
  <td><button data-target="modal"  data-auction-id="<%= auction.auction_id  %>" class="btn waves-effect waves-light modal-trigger red x-modal">Zgłoś do kontroli</button></td>
  <td><a href="#" data-activates="slide-out" class="btn waves-effect waves-light x-drawer-button">Szczegóły</a></td>
</tr>

app/views/panel/auctions/index.html.erb
<header class="page-header x-header">
  <div class="layout-wrapper page-header__content">
    <a href="/" class="brand">VATmobil</a>
    <ul class="main-nav">
      <li><a href="#">Lista aukcji</a></li>
      <li><a href="#">Statystyki</a></li>
    </ul>
    <div class="page-header__options">
      <a class="dropdown-button user-menu-trigger" href="#" data-activates="dropdown-settings" data-stoppropagation="true">vatman@vatman.com</a>
      <ul id="dropdown-settings" class="dropdown-content">
        <li><a href="#!">Ustawienia</a></li>
        <li><a href="#!">Pomoc</a></li>
        <li><%= link_to('Wyloguj się', destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
  </div>
</header>
<main class="layout-wrapper">
  <aside class="data-summary">
    <dl>
      <dt>Ilość rekordów:</dt>
      <dd><%= Auction.count %></dd>
    </dl>
    <dl>
      <dt>Podejrzane:</dt> <dd><%= Auction.where(fraud_possibility: true).count %></dd></dl>
    <dl><dt>Ostatnia aktualizacja:</dt>
      <dd><%= Auction.maximum(:updated_at) %></dd></dl>
    <%= link_to 'Pobierz CSV', panel_auctions_export_path, class: 'btn waves-effect waves-light export-data' %>
  </aside>
  <h2 class="section-header">Lista aukcji</h2>
  <div class="table-wrapper">
    <table class="bordered table-files x-table" id="table-data">
      <thead>
        <tr>
          <th>ID aukcji</th>
          <th class="table__main-col">Przedmiot auckji</th>
          <th>Kwota</th>
          <th>Status</th>
          <th>Zgłoszenie</th>
          <th>Akcje</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial:  'panel/auctions/auction', collection: @auctions %>
      </tbody>
    </table>
  </div>
  <h2 class="section-header">Statystyki podejrzanych rekordów z ostatnich 5 dni</h2>
  <div class="ct-chart">

  </div>
</main>
<footer class="page-footer">
  <div class="layout-wrapper">
    &copy; 2017 VATmobil
  </div>
</footer>

<div id="modal" class="modal">

    <%= form_for(:report, as: :form_data, url: panel_request_control_path, html: { method: :post }, remote: true ) do |f| %>
      <%= f.hidden_field :auction_id, class: 'x-modal-auction-id' %>

      <div class="modal-content">
        <h4>Zgłoszenie kontroli</h4>
        <p>Czy na pewno chcesz zgłosić podmiot do kontroli?</p>
        <div class="input-field">
          <%= f.text_area :full_description, size: '8x80', class: 'materialize-textarea x-description' %>
          <label for="description">Opcjonalny komentarz</label>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Anuluj</a>
        <button type="submit" class="btn modal-action modal-close waves-effect waves-green x-msg">Zgłoś</button>
      </div>
    <% end %>
</div>
<div id="slide-out" class="side-nav custom-sidebar">
  Dane szczegółowe ...
</div>

app/views/panel/auctions/stats.html.erb
<header class="page-header x-header">
  <div class="layout-wrapper page-header__content">
    <a href="/" class="brand">VATmobil</a>
    <ul class="main-nav">
      <li><%= link_to 'Lista aukcji', panel_list_path %></li>
      <li><%= link_to 'Statystyki', panel_stats_path %></li>
    </ul>
    <div class="page-header__options">
      <a class="dropdown-button user-menu-trigger" href="#" data-activates="dropdown-settings" data-stoppropagation="true">vatman@vatman.com</a>
      <ul id="dropdown-settings" class="dropdown-content">
        <li><a href="#!">Ustawienia</a></li>
        <li><a href="#!">Pomoc</a></li>
        <li><%= link_to('Wyloguj się', destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
  </div>
</header>
<main class="layout-wrapper">
  <aside class="data-summary">
    <dl>
      <dt>Ilość rekordów:</dt>
      <dd><%= Auction.count %></dd>
    </dl>
    <dl>
      <dt>Podejrzane:</dt> <dd><%= Auction.where(fraud_possibility: true).count %></dd></dl>
    <dl><dt>Ostatnia aktualizacja:</dt>
      <dd><%= Auction.maximum(:updated_at) %></dd></dl>
    <%= link_to 'Pobierz CSV', panel_auctions_export_path, class: 'btn waves-effect waves-light export-data' %>
  </aside>

  <h2 class="section-header">Statystyki podejrzanych rekordów z ostatnich 5 dni</h2>
  <div class="ct-chart">

  </div>
</main>
<footer class="page-footer">
  <div class="layout-wrapper">
    &copy; 2017 VATmobil
  </div>
</footer>

<div id="modal" class="modal">

    <%= form_for(:report, as: :form_data, url: panel_request_control_path, html: { method: :post }, remote: true ) do |f| %>
      <%= f.hidden_field :auction_id, class: 'x-modal-auction-id' %>

      <div class="modal-content">
        <h4>Zgłoszenie kontroli</h4>
        <p>Czy na pewno chcesz zgłosić podmiot do kontroli?</p>
        <div class="input-field">
          <%= f.text_area :full_description, size: '8x80', class: 'materialize-textarea x-description' %>
          <label for="description">Opcjonalny komentarz</label>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Anuluj</a>
        <button type="submit" class="btn modal-action modal-close waves-effect waves-green x-msg">Zgłoś</button>
      </div>
    <% end %>
</div>
<div id="slide-out" class="side-nav custom-sidebar">
  Dane szczegółowe ...
</div>